#!/usr/bin/env bash

CWD="$(realpath .)"

function fetch_nixpkgs() {
    URL="$1"
    if [[ ! "$URL" =~ ^https?:\/\/ ]]; then
        URL="https://github.com/NixOS/nixpkgs/archive/$URL.zip"
    fi
    nix-prefetch-url "$URL" --print-path --unpack  | tail -n 1
}

function build_docs() {
    nix-build --argstr path "$(fetch_nixpkgs "$1")"
}

function norm_branch() {
    echo "$branch" | sed 's;[\/:];-;g'
}

function build_branch() {
    echo "$(build_docs "$1")/share/doc"
}

function build_branches() {
    rm -rf target
    mkdir -p target
    for branch in "$@"; do
        norm_branch="$(norm_branch "$branch")"
        OUT_LINK="$(build_branch "$branch")" && {
            pushd "$OUT_LINK" > /dev/null
                mkdir "$CWD/target/$norm_branch"
                find . -type d | while read line; do
                    mkdir -p "$CWD/target/$norm_branch/$line"
                done
                find . -type l | while read line; do
                    cp "$line" "$CWD/target/$norm_branch/$line" --preserve=timestamps
                done
            popd > /dev/null
        }
    done
}

function generate_html() {
    {
    echo '<html>'
        echo '<head>'
            echo '<meta charset="utf-8">'
            echo '<title>Available built documentation</title>'
    echo '<style>'
    echo ' '
    echo '</style>'
        echo '</head>'
        echo '<body>'
            echo '<h1>nixpkgs/NixOS documentation</h1>'
            echo "<p>Generated at $(date)</p>"
            for branch in "$@"; do
                norm_branch="$(norm_branch "$branch")"
                echo "<section id="branch-$norm_branch">"
                    echo "<h1><b>Branch:</b> $branch</h1>"
                    echo '<ul>'
                        echo "<li><a href=\"$norm_branch/nixpkgs/manual.html\">nixpkgs manual</a></li>"
                        echo "<li><a href=\"$norm_branch/nixpkgs/nixpkgs-manual.epub\">nixpkgs manual (epub)</a></li>"
                        echo "<li><a href=\"$norm_branch/nixos/index.html\">NixOS documentation</a></li>"
                        echo "<li><a href=\"$norm_branch/nixos/options.html\">NixOS options</a></li>"
                        echo "<li><a href=\"$norm_branch/nixos/release-notes.html\">NixOS release notes</a></li>"
                    echo '</ul>'
                echo '</section>'
            done
        echo '</body>'
    echo '</html>'
    } > target/index.html
}

build_branches "$@"
generate_html "$@"
